#ifndef DEFINE_H
#define DEFINE_H

#define WIN_WIDTH	750
#define WIN_HEIGHT	560

#define KEYBOARD_POS_X (WIN_WIDTH / 100 * 2)
#define KEYBOARD_POS_Y (WIN_HEIGHT - 100)

#define KEYFIELD_POS_X KEYBOARD_POS_X
#define KEYFIELD_WIDTH (WIN_WIDTH / 15 * 11)//350
#define KEYFIELD_HEIGHT 20
#define KEYFIELD_POS_Y (WIN_HEIGHT - WIN_HEIGHT / 100 * 14)

#define NUM_KEY_PADDING 5
#define NUM_KEY_WIDTH	((KEYFIELD_WIDTH - NUM_KEY_PADDING * 15) / 16)
#define NUM_KEY_HEIGHT	(WIN_HEIGHT / 25)

#define UNLOCK_BUTTON_POS_X (KEYFIELD_WIDTH + 20)
#define UNLOCK_BUTTON_POS_Y KEYFIELD_POS_Y
#define UNLOCK_BUTTON_WIDTH	(WIN_WIDTH / 15 * 3)
#define UNLOCK_BUTTON_HEIGHT KEYFIELD_HEIGHT

#define CLEAR_BUTTON_POS_X (UNLOCK_BUTTON_POS_X)
#define CLEAR_BUTTON_POS_Y (KEYBOARD_POS_Y)
#define CLEAR_BUTTON_WIDTH UNLOCK_BUTTON_WIDTH
#define CLEAR_BUTTON_HEIGHT NUM_KEY_HEIGHT

#endif